// G1000 course lessons (MVP1: Garmin ground lessons 1–8). Each lesson is a list of steps:
//   scene   – 3D scene with camera cues (cockpit nodes from shared/three/c172-panel.js, explode nodes from lru.js)
//   explain – short text, optionally highlighting a part of the 2D G1000
//   task    – a goal checked live against the state: setup (scenario + patch), check(s, ctx), hint, why, demo;
//             view 'explode' runs it on the exploded 3D scene (pick an LRU) instead of the 2D G1000
//   quiz    – multiple choice with an explanation
// Demo steps dispatch G1000 events (an event may be a function of the state, resolved when it runs), can wait
// sim seconds and can "click" a part. scripts/check-g1000-content.mjs replays every demo against the model.
import { MENUS } from '../lib/softkeys.js';
import { pageId } from '../lib/pages.js';
import { guidance } from '../lib/guidance.js';
import { gduPhase, ahrsValid, applyPower } from '../lib/sim.js';
import { nearest, vorByFreq } from '../lib/world.js';
import { angleDiff, norm360 } from '../lib/nav.js';

/** @typedef {{es: string, en: string}} Txt */
/** @typedef {import('../lib/avionics.js').G1000Event} G1000Event */
/** @typedef {{ say: Txt, events?: (G1000Event|((s: any) => G1000Event))[], wait?: number, part?: string }} DemoStep */
/** @typedef {{ scenario: import('../lib/state.js').ScenarioId, apply?: (s: any) => void }} Setup */
/**
 * @typedef {{ kind: 'scene', scene: 'cockpit'|'explode', cues: {focus: string, label?: Txt}[], caption: Txt }
 *   | { kind: 'explain', part?: string, title: Txt, text: Txt }
 *   | { kind: 'task', id: string, view?: 'explode', setup: Setup, part?: string, task: Txt, hint: Txt, why: Txt,
 *       check: (s: any, ctx: {lastPart: string|null}) => boolean, demo: DemoStep[] }
 *   | { kind: 'quiz', id: string, q: Txt, options: Txt[], answer: number, why: Txt }} Step
 * @typedef {{ id: string, n: number, title: Txt, objectives: {es: string[], en: string[]}, steps: Step[] }} Lesson
 */

const L = (es, en) => ({ es, en });
const K = (gdu, id, ring, d = 1) => ({ type: 'knob', gdu, id, ring, d });
const P = (gdu, id) => ({ type: 'push', gdu, id });
const KEY = (gdu, id, long = false) => ({ type: 'key', gdu, id, long });
/** Softkey by label, looked up in the menu shown when the demo step runs. */
const SK = (gdu, label) => (s) => ({ type: 'soft', gdu, n: MENUS[gdu][s[gdu].menu].indexOf(label) });
const TYPE = (gdu, id) => [...id].map((c) => ({ type: 'char', gdu, c }));
const SW = (id, on = true) => ({ type: 'switch', id, on });
const AU = (id) => ({ type: 'audio', id });
const near = (a, b, tol = 0.004) => Math.abs(a - b) <= tol;
const clicked = (part) => (_s, ctx) => ctx.lastPart === part;
const tapDemo = (part, es, en) => [{ say: L(es, en), part }];

/** @type {Lesson[]} */
export const LESSONS = [
  // ------------------------------------------------------------------ 1
  {
    id: 'l1', n: 1,
    title: L('El sistema G1000', 'The G1000 system'),
    objectives: {
      es: ['Nombrar las unidades (LRU) del G1000 y qué hace cada una', 'Seguir el camino de un dato desde el sensor hasta la pantalla', 'Explicar WAAS, LPV y RAIM'],
      en: ['Name the G1000 units (LRUs) and what each one does', 'Follow a piece of data from the sensor to the screen', 'Explain WAAS, LPV and RAIM'],
    },
    steps: [
      { kind: 'scene', scene: 'explode',
        cues: [{ focus: 'all' }, { focus: 'gdu1', label: L('Pantallas GDU 1040', 'GDU 1040 displays') },
          { focus: 'gia1', label: L('GIA 63W: el corazón', 'GIA 63W: the heart') }, { focus: 'airData' }, { focus: 'attitude' }],
        caption: L('El G1000 no es una pantalla: es una red de unidades reemplazables (LRU) unidas por buses de datos. Las pantallas solo muestran lo que les llega.',
          'The G1000 is not a screen: it is a network of line-replaceable units (LRUs) joined by data buses. The displays only show what reaches them.') },
      { kind: 'explain', title: L('Quién hace qué', 'Who does what'),
        text: L('Dos pantallas GDU 1040 (PFD y MFD, idénticas e intercambiables). Dos unidades integradas GIA 63W con GPS/WAAS, COM y NAV. El AHRS GRS 77 da actitud y rumbo (con el magnetómetro GMU 44). El ADC GDC 74A convierte pitot, estática y temperatura en velocidad, altitud y VSI. El GEA 71 lee el motor, el GTX 33 es el transponder y el GMA 1347 el panel de audio.',
          'Two GDU 1040 displays (PFD and MFD, identical and swappable). Two GIA 63W integrated units with GPS/WAAS, COM and NAV. The GRS 77 AHRS gives attitude and heading (with the GMU 44 magnetometer). The GDC 74A ADC turns pitot, static and temperature into airspeed, altitude and VSI. The GEA 71 reads the engine, the GTX 33 is the transponder and the GMA 1347 the audio panel.') },
      { kind: 'task', id: 'l1.ahrs', view: 'explode', setup: { scenario: 'enroute' },
        task: L('Toca la unidad que da la actitud (horizonte) y el rumbo.', 'Tap the unit that provides attitude (horizon) and heading.'),
        hint: L('Son giróscopos y acelerómetros de estado sólido: “Attitude and Heading Reference System”.', 'Solid-state gyros and accelerometers: “Attitude and Heading Reference System”.'),
        why: L('Si el AHRS falla, el horizonte y el rumbo del PFD se cubren con X rojas: vuelas con el horizonte de reserva.', 'If the AHRS fails, the PFD horizon and heading get red X’s: you fly on the standby horizon.'),
        check: clicked('lru.ahrs'), demo: tapDemo('lru.ahrs', 'El GRS 77 (AHRS) alimenta actitud y rumbo.', 'The GRS 77 (AHRS) feeds attitude and heading.') },
      { kind: 'task', id: 'l1.adc', view: 'explode', setup: { scenario: 'enroute' },
        task: L('Toca la unidad que calcula velocidad, altitud y velocidad vertical.', 'Tap the unit that computes airspeed, altitude and vertical speed.'),
        hint: L('Recibe el pitot, la estática y la sonda de temperatura.', 'It receives pitot, static and the temperature probe.'),
        why: L('Con el ADC fallado pierdes las cintas de velocidad y altitud y el VSI; te quedan los instrumentos de reserva.', 'With the ADC failed you lose the airspeed and altitude tapes and the VSI; the standby instruments remain.'),
        check: clicked('lru.adc'), demo: tapDemo('lru.adc', 'El GDC 74A (ADC) es la computadora de datos de aire.', 'The GDC 74A (ADC) is the air data computer.') },
      { kind: 'task', id: 'l1.gia', view: 'explode', setup: { scenario: 'enroute' },
        task: L('Toca una de las unidades que contienen el GPS/WAAS, el COM y el NAV.', 'Tap one of the units that contain GPS/WAAS, COM and NAV.'),
        hint: L('Hay dos, una por pantalla, y no se hablan entre sí directamente.', 'There are two, one per display, and they do not talk to each other directly.'),
        why: L('Cada GIA va emparejada con su pantalla: si una falla, la otra sigue dando GPS y radios.', 'Each GIA is paired with its display: if one fails, the other still provides GPS and radios.'),
        check: clicked('lru.gia'), demo: tapDemo('lru.gia', 'Las GIA 63W integran GPS/WAAS, COM, NAV y el procesamiento.', 'The GIA 63W units integrate GPS/WAAS, COM, NAV and processing.') },
      { kind: 'quiz', id: 'l1.q1', q: L('¿Qué aporta WAAS al GPS del G1000?', 'What does WAAS add to the G1000 GPS?'),
        options: [L('Correcciones y monitoreo de integridad que permiten aproximaciones LPV', 'Corrections and integrity monitoring that allow LPV approaches'),
          L('Datos de actitud de respaldo', 'Backup attitude data'), L('Alertas de terreno', 'Terrain alerts')],
        answer: 0, why: L('WAAS es un SBAS: estaciones en tierra calculan correcciones que llegan por satélite. Mejora precisión e integridad hasta permitir guiado vertical tipo ILS (LPV).',
          'WAAS is an SBAS: ground stations compute corrections broadcast by satellite. It improves accuracy and integrity up to ILS-like vertical guidance (LPV).') },
      { kind: 'quiz', id: 'l1.q2', q: L('RAIM significa…', 'RAIM means…'),
        options: [L('Monitoreo autónomo de integridad en el propio receptor GPS', 'Receiver autonomous integrity monitoring'),
          L('Un modo del radar meteorológico', 'A weather radar mode'), L('El rango máximo de un VOR', 'The maximum range of a VOR')],
        answer: 0, why: L('El receptor compara satélites redundantes para detectar uno erróneo. Con WAAS disponible la predicción de RAIM ya no es necesaria.',
          'The receiver cross-checks redundant satellites to catch a faulty one. With WAAS available, RAIM prediction is no longer needed.') },
      { kind: 'quiz', id: 'l1.q3', q: L('Falla el ADC. ¿Qué ves en el PFD?', 'The ADC fails. What do you see on the PFD?'),
        options: [L('X rojas en velocidad, altitud y VSI', 'Red X’s on airspeed, altitude and VSI'), L('X roja en el horizonte', 'A red X on the horizon'),
          L('Las radios COM se apagan', 'The COM radios switch off')],
        answer: 0, why: L('El G1000 nunca muestra un dato dudoso: lo tacha con una X roja. Sin ADC no hay datos de aire.', 'The G1000 never shows doubtful data: it crosses it out with a red X. Without the ADC there is no air data.') },
    ],
  },
  // ------------------------------------------------------------------ 2
  {
    id: 'l2', n: 2,
    title: L('Del six-pack al PFD', 'From six-pack to PFD'),
    objectives: {
      es: ['Encontrar en el PFD cada instrumento del six-pack', 'Ajustar el altímetro y la altitud seleccionada'],
      en: ['Find every six-pack instrument on the PFD', 'Set the altimeter and the selected altitude'],
    },
    steps: [
      { kind: 'scene', scene: 'cockpit',
        cues: [{ focus: 'standby', label: L('Instrumentos de reserva', 'Standby instruments') }, { focus: 'pfd', label: L('PFD', 'PFD') }],
        caption: L('Los seis instrumentos clásicos siguen ahí, pero dibujados alrededor del horizonte. Los de reserva (velocidad, horizonte, altímetro) quedan para cuando el G1000 falla.',
          'The six classic instruments are still there, drawn around the horizon. The standby ones (airspeed, horizon, altimeter) are for when the G1000 fails.') },
      { kind: 'explain', part: 'pfd.att', title: L('Mismo T básico', 'Same basic T'),
        text: L('Velocidad a la izquierda, actitud al centro, altitud a la derecha y rumbo (HSI) abajo: el mismo “T” del six-pack. El VSI está junto a la cinta de altitud y el coordinador de giro es el pequeño trapecio bajo el puntero de alabeo.',
          'Airspeed on the left, attitude in the middle, altitude on the right and heading (HSI) below: the same “T” as the six-pack. The VSI sits next to the altitude tape and the turn coordinator is the small trapezoid under the roll pointer.') },
      { kind: 'task', id: 'l2.ias', setup: { scenario: 'enroute' }, part: 'pfd.ias',
        task: L('Toca la cinta de velocidad.', 'Tap the airspeed tape.'), hint: L('A la izquierda del horizonte, con arcos de colores.', 'Left of the horizon, with coloured arcs.'),
        why: L('Los arcos blanco, verde, amarillo y la línea roja son los mismos del anemómetro clásico, pero junto al número exacto.', 'The white, green and yellow arcs and the red line are the classic airspeed indicator ones, next to the exact number.'),
        check: clicked('pfd.ias'), demo: tapDemo('pfd.ias', 'La cinta de velocidad indicada (IAS).', 'The indicated airspeed (IAS) tape.') },
      { kind: 'task', id: 'l2.slip', setup: { scenario: 'enroute' }, part: 'pfd.slip',
        task: L('Toca el indicador de derrape (la “bola”).', 'Tap the slip/skid indicator (the “ball”).'), hint: L('El trapecio blanco bajo el triángulo de alabeo.', 'The white trapezoid under the roll triangle.'),
        why: L('Se centra con el pie: “pisa el trapecio” igual que pisabas la bola.', 'You centre it with your feet: “step on the trapezoid” as you stepped on the ball.'),
        check: clicked('pfd.slip'), demo: tapDemo('pfd.slip', 'El trapecio es la bola del coordinador.', 'The trapezoid is the turn coordinator ball.') },
      { kind: 'task', id: 'l2.hsi', setup: { scenario: 'enroute' }, part: 'pfd.hsi',
        task: L('Toca el HSI.', 'Tap the HSI.'), hint: L('La rosa de rumbos de abajo.', 'The compass rose at the bottom.'),
        why: L('El HSI une el giroscopio direccional y el CDI: rumbo y desviación de curso en un solo instrumento.', 'The HSI merges the heading indicator and the CDI: heading and course deviation in one instrument.'),
        check: clicked('pfd.hsi'), demo: tapDemo('pfd.hsi', 'El HSI: rosa de rumbos con la aguja de curso.', 'The HSI: compass rose with the course needle.') },
      { kind: 'task', id: 'l2.baro', setup: { scenario: 'enroute', apply: (s) => { s.sel.baro = 29.92; } }, part: 'k.crsbaro',
        task: L('El QNH de la zona es 30.12. Ajusta el altímetro con el anillo BARO.', 'The area altimeter setting is 30.12. Set it with the BARO ring.'),
        hint: L('Anillo grande del knob CRS/BARO; el valor se ve bajo la cinta de altitud.', 'Large ring of the CRS/BARO knob; the value shows under the altitude tape.'),
        why: L('Con el ajuste equivocado el altímetro miente: 0.20 inHg son 200 ft.', 'With the wrong setting the altimeter lies: 0.20 inHg is 200 ft.'),
        check: (s) => near(s.sel.baro, 30.12), demo: [{ say: L('Gira BARO 20 pasos (0.01 cada uno).', 'Turn BARO 20 clicks (0.01 each).'), events: [K('pfd', 'crsbaro', 'outer', 20)] }] },
      { kind: 'task', id: 'l2.selAlt', setup: { scenario: 'enroute' }, part: 'pfd.selAlt',
        task: L('Selecciona 5500 ft con el knob ALT y mira subir al instructor.', 'Select 5500 ft with the ALT knob and watch the instructor climb.'),
        hint: L('Anillo grande: miles; pequeño: cientos. La altitud seleccionada se ve en cian sobre la cinta.', 'Large ring: thousands; small: hundreds. The selected altitude shows in cyan above the tape.'),
        why: L('En un C172 sin autopiloto es una referencia con alerta: el G1000 avisa al acercarte y al desviarte.', 'In a C172 without autopilot it is a reference with alerting: the G1000 warns when approaching and when deviating.'),
        check: (s) => s.sel.alt === 5500, demo: [{ say: L('ALT grande +1 (5500).', 'ALT large +1 (5500).'), events: [K('pfd', 'alt', 'outer', 1)] }] },
      { kind: 'quiz', id: 'l2.q1', q: L('¿Dónde está el VSI en el PFD?', 'Where is the VSI on the PFD?'),
        options: [L('A la derecha de la cinta de altitud', 'Right of the altitude tape'), L('Debajo del HSI', 'Below the HSI'), L('Solo en el MFD', 'Only on the MFD')],
        answer: 0, why: L('Escala vertical junto al altímetro, con el valor exacto en la aguja.', 'A vertical scale next to the altimeter, with the exact value on the pointer.') },
      { kind: 'quiz', id: 'l2.q2', q: L('La línea magenta que crece junto a la cinta de velocidad indica…', 'The magenta line growing next to the airspeed tape shows…'),
        options: [L('La velocidad que tendrás en 6 segundos', 'The airspeed you will have in 6 seconds'), L('La velocidad máxima', 'The maximum speed'), L('La velocidad del viento', 'The wind speed')],
        answer: 0, why: L('Es el vector de tendencia: anticipa la velocidad si nada cambia.', 'It is the trend vector: it predicts airspeed if nothing changes.') },
      { kind: 'quiz', id: 'l2.q3', q: L('Una franja de rayas rojas y blancas en la parte alta de la cinta de velocidad es…', 'A red-and-white striped band at the top of the airspeed tape is…'),
        options: [L('VNE, la velocidad que nunca debes exceder', 'VNE, the never-exceed speed'), L('La velocidad de pérdida', 'The stall speed'), L('Un fallo del ADC', 'An ADC failure')],
        answer: 0, why: L('Es la línea roja del anemómetro clásico.', 'It is the red line of the classic airspeed indicator.') },
    ],
  },
  // ------------------------------------------------------------------ 3
  {
    id: 'l3', n: 3,
    title: L('Encendido y autotest', 'Power-up and self-test'),
    objectives: {
      es: ['Encender el sistema en orden', 'Reconocer el alineamiento del AHRS y la página de base de datos', 'Revisar el EIS y ajustar el altímetro en tierra'],
      en: ['Power the system up in order', 'Recognise AHRS alignment and the database page', 'Check the EIS and set the altimeter on the ground'],
    },
    steps: [
      { kind: 'scene', scene: 'cockpit',
        cues: [{ focus: 'master', label: L('MASTER', 'MASTER') }, { focus: 'avionics', label: L('AVIONICS', 'AVIONICS') }, { focus: 'pfd' }, { focus: 'mfd' }],
        caption: L('En el C172 G1000 el MASTER enciende el PFD (bus esencial) y el AVIONICS el MFD y el resto de la aviónica.',
          'In the G1000 C172 the MASTER powers the PFD (essential bus) and AVIONICS the MFD and the rest of the avionics.') },
      { kind: 'task', id: 'l3.master', setup: { scenario: 'cold' }, part: 'sw.master',
        task: L('Enciende el MASTER.', 'Switch the MASTER on.'), hint: L('Interruptor rojo a la izquierda del panel.', 'Red switch on the left of the panel.'),
        why: L('El PFD arranca solo con el MASTER: así tienes instrumentos de vuelo aunque falle el bus de aviónica.', 'The PFD starts with the MASTER alone: you keep flight instruments even if the avionics bus fails.'),
        check: (s) => s.power.master, demo: [{ say: L('MASTER en ON.', 'MASTER ON.'), events: [SW('master')] }] },
      { kind: 'task', id: 'l3.align', setup: { scenario: 'cold', apply: (s) => { s.power.master = true; applyPower(s); } }, part: 'pfd.att',
        task: L('Espera a que desaparezcan las X rojas del horizonte y del rumbo.', 'Wait for the red X’s on the horizon and heading to clear.'),
        hint: L('Primero se valida el ADC (velocidad y altitud), luego se alinea el AHRS. No muevas el avión.', 'First the ADC (airspeed and altitude) validates, then the AHRS aligns. Do not move the aircraft.'),
        why: L('Una X roja es información no válida. No despegues hasta que todas desaparezcan.', 'A red X is invalid information. Do not take off until all of them are gone.'),
        check: (s) => ahrsValid(s), demo: [{ say: L('Esperamos el alineamiento…', 'Waiting for the alignment…'), wait: 14 }] },
      { kind: 'task', id: 'l3.avionics', setup: { scenario: 'cold', apply: (s) => { s.power.master = true; applyPower(s); } }, part: 'key.ent',
        task: L('Enciende AVIONICS y, cuando el MFD muestre la base de datos, acéptala con ENT.', 'Switch AVIONICS on and, when the MFD shows the database page, accept it with ENT.'),
        hint: L('La tecla ENT del MFD.', 'The MFD ENT key.'),
        why: L('Comprueba que la base de datos de navegación esté vigente: es obligatorio para usar el GPS en IFR.', 'Check that the navigation database is current: it is mandatory to use the GPS for IFR.'),
        check: (s) => gduPhase(s, 'mfd') === 'ready',
        demo: [{ say: L('AVIONICS en ON.', 'AVIONICS ON.'), events: [SW('avionics')] }, { say: L('El MFD arranca…', 'The MFD boots…'), wait: 4 },
          { say: L('ENT para aceptar la base de datos.', 'ENT to accept the database.'), events: [KEY('mfd', 'ent')] }] },
      { kind: 'task', id: 'l3.engine', setup: { scenario: 'ground', apply: (s) => { s.power.engine = false; s.ac.rpm = 0; } }, part: 'mfd.eis',
        task: L('Arranca el motor y revisa el EIS: RPM cerca de 1000 y presión de aceite en verde.', 'Start the engine and check the EIS: RPM near 1000 and oil pressure in the green.'),
        hint: L('Interruptor de arranque (llave) y la franja izquierda del MFD.', 'Starter (key) switch and the left strip of the MFD.'),
        why: L('El EIS reemplaza los relojes de motor; las agujas y colores bastan para un vistazo rápido.', 'The EIS replaces the engine gauges; pointers and colours are enough for a quick glance.'),
        check: (s) => s.power.engine && s.ac.rpm > 900, demo: [{ say: L('Arranque.', 'Start.'), events: [SW('engine')] }, { say: L('RPM estabilizándose.', 'RPM settling.'), wait: 4 }] },
      { kind: 'task', id: 'l3.baro', setup: { scenario: 'ground', apply: (s) => { s.sel.baro = 29.92; } }, part: 'pfd.alt',
        task: L('SQ01 está a 45 ft. Gira BARO hasta que el altímetro marque la elevación del campo.', 'SQ01 is at 45 ft. Turn BARO until the altimeter reads the field elevation.'),
        hint: L('Con 30.12 el altímetro marca 45 ft.', 'With 30.12 the altimeter reads 45 ft.'),
        why: L('En tierra, sin QNH, ajustas a la elevación del aeródromo: es la comprobación clásica del altímetro.', 'On the ground, without a setting, you set field elevation: it is the classic altimeter check.'),
        check: (s) => near(s.sel.baro, 30.12), demo: [{ say: L('BARO +20 pasos.', 'BARO +20 clicks.'), events: [K('pfd', 'crsbaro', 'outer', 20)] }] },
      { kind: 'quiz', id: 'l3.q1', q: L('¿Qué alimenta el interruptor AVIONICS?', 'What does the AVIONICS switch power?'),
        options: [L('El MFD y el resto del bus de aviónica', 'The MFD and the rest of the avionics bus'), L('Solo el PFD', 'Only the PFD'), L('El motor de arranque', 'The starter')],
        answer: 0, why: L('El PFD cuelga del bus esencial (MASTER); el MFD del bus de aviónica.', 'The PFD hangs on the essential bus (MASTER); the MFD on the avionics bus.') },
      { kind: 'quiz', id: 'l3.q2', q: L('Una X roja sobre un instrumento del PFD significa…', 'A red X over a PFD instrument means…'),
        options: [L('Que ese dato no es válido', 'That data is not valid'), L('Que está en modo prueba', 'That it is in test mode'), L('Que hay tráfico', 'That there is traffic')],
        answer: 0, why: L('El G1000 tacha lo que no puede garantizar: falla del sensor o aún sin datos.', 'The G1000 crosses out what it cannot vouch for: a failed sensor or no data yet.') },
      { kind: 'quiz', id: 'l3.q3', q: L('¿Por qué no hay que mover el avión durante el alineamiento del AHRS?', 'Why should the aircraft not move during AHRS alignment?'),
        options: [L('El AHRS necesita estar quieto para fijar su referencia', 'The AHRS needs to be still to settle its reference'), L('Para no gastar combustible', 'To save fuel'), L('No importa', 'It does not matter')],
        answer: 0, why: L('Moverse alarga el alineamiento; el GRS 77 puede alinearse en movimiento, pero tarda más.', 'Moving lengthens the alignment; the GRS 77 can align while moving, but it takes longer.') },
    ],
  },
  // ------------------------------------------------------------------ 4
  {
    id: 'l4', n: 4,
    title: L('Transponder', 'Transponder'),
    objectives: {
      es: ['Cambiar el modo del transponder', 'Introducir un código y hacer IDENT', 'Usar la tecla VFR'],
      en: ['Change the transponder mode', 'Enter a code and IDENT', 'Use the VFR key'],
    },
    steps: [
      { kind: 'scene', scene: 'cockpit', cues: [{ focus: 'softkeysPfd', label: L('Softkeys del PFD', 'PFD softkeys') }],
        caption: L('El transponder no tiene panel propio: se maneja con las softkeys del PFD y su estado se ve en la caja de abajo a la derecha.',
          'The transponder has no panel of its own: you run it with the PFD softkeys and its status shows in the box at the bottom right.') },
      { kind: 'explain', part: 'pfd.xpdrBox', title: L('Modos', 'Modes'),
        text: L('STBY: encendido pero sin responder. ON: responde con el código (modo A). ALT: además envía la altitud (modo C/S). En vuelo usa ALT salvo que ATC pida otra cosa.',
          'STBY: on but not replying. ON: replies with the code (mode A). ALT: also sends altitude (mode C/S). In flight use ALT unless ATC asks otherwise.') },
      { kind: 'task', id: 'l4.alt', setup: { scenario: 'ground', apply: (s) => { s.xpdr.mode = 'STBY'; } }, part: 'pfd.xpdrBox',
        task: L('Antes de entrar a la pista, pasa el transponder de STBY a ALT.', 'Before entering the runway, switch the transponder from STBY to ALT.'),
        hint: L('XPDR y luego ALT.', 'XPDR, then ALT.'), why: L('Con ALT el radar y el TCAS de otros aviones te ven con altitud.', 'With ALT, radar and other aircraft’s TCAS see you with altitude.'),
        check: (s) => s.xpdr.mode === 'ALT', demo: [{ say: L('XPDR → ALT.', 'XPDR → ALT.'), events: [SK('pfd', 'XPDR'), SK('pfd', 'ALT')] }] },
      { kind: 'task', id: 'l4.code', setup: { scenario: 'enroute', apply: (s) => { s.xpdr.code = '1200'; } }, part: 'pfd.xpdrBox',
        task: L('ATC te asigna 4721. Introdúcelo.', 'ATC assigns 4721. Enter it.'),
        hint: L('XPDR → CODE y las cifras con las softkeys 0–7; con la cuarta cifra el código queda activo.', 'XPDR → CODE and the digits on softkeys 0–7; the code activates with the fourth digit.'),
        why: L('Los códigos usan solo cifras 0–7 (octal): por eso no hay 8 ni 9.', 'Codes use only digits 0–7 (octal): that is why there is no 8 or 9.'),
        check: (s) => s.xpdr.code === '4721',
        demo: [{ say: L('XPDR → CODE.', 'XPDR → CODE.'), events: [SK('pfd', 'XPDR'), SK('pfd', 'CODE')] },
          { say: L('4 7 2 1.', '4 7 2 1.'), events: [SK('pfd', '4'), SK('pfd', '7'), SK('pfd', '2'), SK('pfd', '1')] }] },
      { kind: 'task', id: 'l4.ident', setup: { scenario: 'enroute' }, part: 'pfd.xpdrBox',
        task: L('ATC dice “squawk ident”. Pulsa IDENT.', 'ATC says “squawk ident”. Press IDENT.'),
        hint: L('IDENT está en la fila principal de softkeys.', 'IDENT is on the main softkey row.'),
        why: L('Tu blanco destella en la pantalla del controlador durante unos 18 s.', 'Your target flashes on the controller’s screen for about 18 s.'),
        check: (s) => s.xpdr.ident > 0, demo: [{ say: L('IDENT.', 'IDENT.'), events: [SK('pfd', 'IDENT')] }] },
      { kind: 'task', id: 'l4.vfr', setup: { scenario: 'enroute' }, part: 'pfd.xpdrBox',
        task: L('Terminó el servicio radar: vuelve al código VFR.', 'Radar service terminated: go back to the VFR code.'),
        hint: L('XPDR → VFR pone 1200 de un toque.', 'XPDR → VFR sets 1200 in one press.'),
        why: L('1200 es el código VFR en EE. UU.; en otros países puede ser 7000. Consulta el AIP.', '1200 is the US VFR code; elsewhere it can be 7000. Check the AIP.'),
        check: (s) => s.xpdr.code === '1200', demo: [{ say: L('XPDR → VFR.', 'XPDR → VFR.'), events: [SK('pfd', 'XPDR'), SK('pfd', 'VFR')] }] },
      { kind: 'quiz', id: 'l4.q1', q: L('¿Qué añade el modo ALT respecto a ON?', 'What does ALT add over ON?'),
        options: [L('La altitud de presión', 'Pressure altitude'), L('La velocidad', 'Airspeed'), L('El rumbo', 'Heading')], answer: 0,
        why: L('La altitud viene del ADC, siempre referida a 29.92 sin importar tu ajuste BARO.', 'Altitude comes from the ADC, always referenced to 29.92 whatever your BARO setting.') },
      { kind: 'quiz', id: 'l4.q2', q: L('Código de emergencia general:', 'General emergency code:'),
        options: [L('7700', '7700'), L('7600', '7600'), L('7500', '7500')], answer: 0,
        why: L('7700 emergencia, 7600 fallo de comunicaciones, 7500 interferencia ilícita.', '7700 emergency, 7600 lost communications, 7500 unlawful interference.') },
      { kind: 'quiz', id: 'l4.q3', q: L('¿Por qué el teclado de código no tiene 8 ni 9?', 'Why does the code keypad have no 8 or 9?'),
        options: [L('Los códigos son octales (0–7)', 'Codes are octal (0–7)'), L('Por espacio en la pantalla', 'Screen space'), L('Están en el MFD', 'They are on the MFD')], answer: 0,
        why: L('4 cifras octales dan 4096 códigos.', '4 octal digits give 4096 codes.') },
    ],
  },
  // ------------------------------------------------------------------ 5
  {
    id: 'l5', n: 5,
    title: L('COM y panel de audio', 'COM and audio panel'),
    objectives: {
      es: ['Sintonizar en standby y pasar a activa', 'Cargar frecuencias desde la base de datos', 'Elegir con qué radio hablas y cuáles escuchas'],
      en: ['Tune the standby and swap to active', 'Load frequencies from the database', 'Choose which radio you talk on and which you listen to'],
    },
    steps: [
      { kind: 'scene', scene: 'cockpit', cues: [{ focus: 'comKnob', label: L('Knob COM', 'COM knob') }, { focus: 'audio', label: L('Panel de audio', 'Audio panel') }],
        caption: L('Las frecuencias COM están arriba a la derecha del PFD. El knob COM sintoniza la standby; la tecla ⇆ las intercambia.',
          'COM frequencies are at the top right of the PFD. The COM knob tunes the standby; the ⇆ key swaps them.') },
      { kind: 'explain', part: 'pfd.comBox', title: L('Activa, standby y caja cian', 'Active, standby and the cyan box'),
        text: L('Izquierda: activa (en verde la que transmite). Derecha: standby. La caja cian marca la radio que estás sintonizando; empujar el knob COM la cambia entre COM1 y COM2.',
          'Left: active (the transmitting one in green). Right: standby. The cyan box marks the radio being tuned; pushing the COM knob switches it between COM1 and COM2.') },
      { kind: 'task', id: 'l5.tune', setup: { scenario: 'enroute', apply: (s) => { s.com[0] = { act: 124.35, stby: 121.5 }; s.comTune = 0; } }, part: 'k.com',
        task: L('Sintoniza la torre de SQ01, 118.300, en la standby de COM1.', 'Tune SQ01 tower, 118.300, in the COM1 standby.'),
        hint: L('Anillo grande: MHz. Pequeño: pasos de 25 kHz.', 'Large ring: MHz. Small: 25 kHz steps.'),
        why: L('Preparas la siguiente frecuencia sin perder la actual.', 'You prepare the next frequency without losing the current one.'),
        check: (s) => near(s.com[0].stby, 118.3, 0.0005),
        demo: [{ say: L('Grande −3: 118.', 'Large −3: 118.'), events: [K('pfd', 'com', 'outer', -3)] }, { say: L('Pequeño −8: .300.', 'Small −8: .300.'), events: [K('pfd', 'com', 'inner', -8)] }] },
      { kind: 'task', id: 'l5.swap', setup: { scenario: 'enroute', apply: (s) => { s.com[0] = { act: 124.35, stby: 118.3 }; s.comTune = 0; } }, part: 'key.comSwap',
        task: L('Pasa la torre a activa.', 'Make the tower active.'), hint: L('La tecla ⇆ junto al knob COM.', 'The ⇆ key next to the COM knob.'),
        why: L('Si la torre no contesta, ⇆ de nuevo te devuelve a la anterior.', 'If the tower does not answer, ⇆ again takes you back to the previous one.'),
        check: (s) => near(s.com[0].act, 118.3, 0.0005), demo: [{ say: L('⇆.', '⇆.'), events: [KEY('pfd', 'comSwap')] }] },
      { kind: 'task', id: 'l5.wpt', setup: { scenario: 'enroute', apply: (s) => { s.com[0].stby = 121.5; s.comTune = 0; } }, part: 'mfd.page',
        task: L('Carga la torre de SQ04 desde WPT › Airport Information del MFD.', 'Load SQ04 tower from WPT › Airport Information on the MFD.'),
        hint: L('FMS grande al grupo WPT, empuja FMS, escribe SQ04 y ENT; baja a la frecuencia TWR y ENT.', 'Large FMS to the WPT group, push FMS, type SQ04 and ENT; move to the TWR frequency and ENT.'),
        why: L('Leer la frecuencia de la base de datos evita errores de copia.', 'Taking the frequency from the database avoids copy errors.'),
        check: (s) => near(s.com[0].stby, 119.1, 0.0005),
        demo: [{ say: L('Grupo WPT y cursor.', 'WPT group and cursor.'), events: [K('mfd', 'fms', 'outer', 1), P('mfd', 'fms')] },
          { say: L('SQ04 y ENT.', 'SQ04 and ENT.'), events: [...TYPE('mfd', 'SQ04'), KEY('mfd', 'ent')] },
          { say: L('Cursor a TWR 119.100 y ENT.', 'Cursor to TWR 119.100 and ENT.'), events: [K('mfd', 'fms', 'outer', 3), KEY('mfd', 'ent')] }] },
      { kind: 'task', id: 'l5.com2', setup: { scenario: 'enroute' }, part: 'audio.panel',
        task: L('Escucha también COM2 (ATIS) sin dejar de transmitir por COM1.', 'Also listen to COM2 (ATIS) while still transmitting on COM1.'),
        hint: L('Tecla COM2 del panel de audio (no COM2 MIC).', 'COM2 key on the audio panel (not COM2 MIC).'),
        why: L('Oyes el ATIS sin perder a ATC.', 'You hear the ATIS without losing ATC.'),
        check: (s) => s.audio.com2 && s.audio.mic === 0, demo: [{ say: L('COM2.', 'COM2.'), events: [AU('com2')] }] },
      { kind: 'task', id: 'l5.mic2', setup: { scenario: 'enroute' }, part: 'audio.panel',
        task: L('Ahora transmite por COM2.', 'Now transmit on COM2.'), hint: L('COM2 MIC.', 'COM2 MIC.'),
        why: L('MIC elige el transmisor y activa también su escucha.', 'MIC selects the transmitter and also turns on its audio.'),
        check: (s) => s.audio.mic === 1, demo: [{ say: L('COM2 MIC.', 'COM2 MIC.'), events: [AU('com2mic')] }] },
      { kind: 'quiz', id: 'l5.q1', q: L('Girar el knob COM cambia…', 'Turning the COM knob changes…'),
        options: [L('La frecuencia standby de la radio en la caja cian', 'The standby frequency of the radio in the cyan box'), L('La frecuencia activa', 'The active frequency'), L('El volumen', 'The volume')], answer: 0,
        why: L('Nunca se sintoniza directamente la activa: así no pierdes la comunicación por un error.', 'You never tune the active directly: a slip will not cut you off.') },
      { kind: 'quiz', id: 'l5.q2', q: L('Con COM1 MIC y COM2 activados en el panel de audio, ¿qué oyes?', 'With COM1 MIC and COM2 selected on the audio panel, what do you hear?'),
        options: [L('COM1 y COM2', 'COM1 and COM2'), L('Solo COM1', 'Only COM1'), L('Solo COM2', 'Only COM2')], answer: 0,
        why: L('Transmites por COM1 y escuchas ambas.', 'You transmit on COM1 and hear both.') },
      { kind: 'quiz', id: 'l5.q3', q: L('¿Dónde encuentras las frecuencias de un aeródromo en el MFD?', 'Where do you find an airport’s frequencies on the MFD?'),
        options: [L('WPT › Airport Information y NRST', 'WPT › Airport Information and NRST'), L('AUX › GPS Status', 'AUX › GPS Status'), L('En el EIS', 'In the EIS')], answer: 0,
        why: L('Ambas páginas permiten cargar la frecuencia con ENT.', 'Both pages let you load the frequency with ENT.') },
    ],
  },
  // ------------------------------------------------------------------ 6
  {
    id: 'l6', n: 6,
    title: L('Navegación: VOR y GPS', 'Navigation: VOR and GPS'),
    objectives: {
      es: ['Sintonizar e identificar un VOR y volar un radial', 'Hacer Direct-To por identificador y desde NRST', 'Usar OBS hacia un waypoint'],
      en: ['Tune and identify a VOR and fly a radial', 'Direct-To by identifier and from NRST', 'Use OBS to a waypoint'],
    },
    steps: [
      { kind: 'scene', scene: 'cockpit',
        cues: [{ focus: 'navKnob', label: L('Knob NAV', 'NAV knob') }, { focus: 'crsKnob', label: L('CRS', 'CRS') }, { focus: 'dtoKey', label: L('D→', 'D→') }],
        caption: L('El HSI muestra la fuente de navegación que elijas con la softkey CDI: GPS en magenta, VOR en verde.',
          'The HSI shows the navigation source you pick with the CDI softkey: GPS in magenta, VOR in green.') },
      { kind: 'task', id: 'l6.vor', setup: { scenario: 'enroute', apply: (s) => { s.nav[0] = { act: 110.0, stby: 110.0 }; s.navTune = 0; } }, part: 'k.nav',
        task: L('Pon ALB, 113.30, como frecuencia activa de NAV1.', 'Make ALB, 113.30, the NAV1 active frequency.'),
        hint: L('Knob NAV (grande MHz, pequeño 50 kHz) y la tecla ⇆ de NAV.', 'NAV knob (large MHz, small 50 kHz) and the NAV ⇆ key.'),
        why: L('Las frecuencias NAV están arriba a la izquierda del PFD.', 'NAV frequencies are at the top left of the PFD.'),
        check: (s) => near(s.nav[0].act, 113.3, 0.0005),
        demo: [{ say: L('Grande +3, pequeño +6.', 'Large +3, small +6.'), events: [K('pfd', 'nav', 'outer', 3), K('pfd', 'nav', 'inner', 6)] },
          { say: L('⇆ NAV.', 'NAV ⇆.'), events: [KEY('pfd', 'navSwap')] }] },
      { kind: 'task', id: 'l6.ident', setup: { scenario: 'enroute', apply: (s) => { s.nav[0].act = 113.3; s.audio.nav1 = false; } }, part: 'audio.panel',
        task: L('Identifica la estación: escucha NAV1.', 'Identify the station: listen to NAV1.'),
        hint: L('Tecla NAV1 del panel de audio; el identificador también aparece junto a la frecuencia.', 'NAV1 key on the audio panel; the identifier also shows next to the frequency.'),
        why: L('Nunca navegues con un VOR sin identificarlo: puede estar en mantenimiento o ser otro.', 'Never navigate on a VOR you have not identified: it may be under maintenance or be a different one.'),
        check: (s) => s.audio.nav1 && vorByFreq(s.nav[0].act)?.id === 'ALB', demo: [{ say: L('NAV1: ·— ·—·· —··· = ALB.', 'NAV1: ·— ·—·· —··· = ALB.'), events: [AU('nav1')] }] },
      { kind: 'task', id: 'l6.radial', setup: { scenario: 'enroute', apply: (s) => { s.nav[0].act = 113.3; s.sel.crs1 = 0; } }, part: 'pfd.hsi',
        task: L('Pon el CDI en VOR1 y centra la aguja con indicación TO.', 'Set the CDI to VOR1 and centre the needle with a TO indication.'),
        hint: L('Softkey CDI hasta VOR1; empuja CRS para centrar con TO, o gira CRS.', 'CDI softkey to VOR1; push CRS to centre with TO, or turn CRS.'),
        why: L('El curso centrado con TO es el rumbo directo a la estación.', 'The centred course with TO is the direct course to the station.'),
        check: (s) => { const g = guidance(s); return s.pfd.cdi === 'VOR1' && g.valid && g.toFrom === 'TO' && Math.abs(g.defl) < 0.2; },
        demo: [{ say: L('CDI → VOR1.', 'CDI → VOR1.'), events: [SK('pfd', 'CDI')] }, { say: L('Empuja CRS.', 'Push CRS.'), events: [P('pfd', 'crsbaro')] }] },
      { kind: 'task', id: 'l6.dto', setup: { scenario: 'enroute' }, part: 'key.dto',
        task: L('Vuela directo a SQ04.', 'Fly direct to SQ04.'),
        hint: L('D→, escribe SQ04 (o FMS pequeño), ENT y ENT para activar.', 'D→, type SQ04 (or small FMS), ENT and ENT to activate.'),
        why: L('El G1000 traza una línea magenta desde donde estás; el instructor la vuela.', 'The G1000 draws a magenta line from where you are; the instructor flies it.'),
        check: (s) => s.gps.dto?.id === 'SQ04' && s.pfd.cdi === 'GPS',
        demo: [{ say: L('D→ y SQ04.', 'D→ and SQ04.'), events: [KEY('pfd', 'dto'), ...TYPE('pfd', 'SQ04')] }, { say: L('ENT, ENT.', 'ENT, ENT.'), events: [KEY('pfd', 'ent'), KEY('pfd', 'ent')] }] },
      { kind: 'task', id: 'l6.nrst', setup: { scenario: 'enroute', apply: (s) => { s.ac.lat = 10.5; s.ac.lon = -64.3; } }, part: 'pfd.nrst',
        task: L('Emergencia simulada: directo al aeródromo más cercano desde NRST del PFD.', 'Simulated emergency: direct to the nearest airport from the PFD NRST.'),
        hint: L('NRST, empuja FMS (el primero es el más cercano), D→, ENT, ENT.', 'NRST, push FMS (the first one is the nearest), D→, ENT, ENT.'),
        why: L('Cuatro pulsaciones a un aeródromo: el uso más valioso del GPS en una emergencia.', 'Four presses to an airport: the most valuable use of GPS in an emergency.'),
        check: (s) => !!s.gps.dto && s.gps.dto.id === nearest(s.gps.dto.from)[0].apt.id,
        demo: [{ say: L('NRST y cursor.', 'NRST and cursor.'), events: [SK('pfd', 'NRST'), P('pfd', 'fms')] }, { say: L('D→ ENT ENT.', 'D→ ENT ENT.'), events: [KEY('pfd', 'dto'), KEY('pfd', 'ent'), KEY('pfd', 'ent')] }] },
      { kind: 'task', id: 'l6.obs', setup: { scenario: 'enroute', apply: (s) => { s.gps.fpl = { legs: ['SQ01', 'MIRA', 'SQ02'], active: 1 }; } }, part: 'pfd.hsi',
        task: L('Llega a MIRA con rumbo 090: activa OBS y pon el curso en 090.', 'Arrive at MIRA on course 090: activate OBS and set the course to 090.'),
        hint: L('Softkey OBS y gira CRS.', 'OBS softkey and turn CRS.'),
        why: L('OBS fija un curso hacia el waypoint y detiene la secuencia del plan, como un VOR virtual.', 'OBS sets a course to the waypoint and stops plan sequencing, like a virtual VOR.'),
        check: (s) => s.pfd.obs && s.sel.obsCrs === 90,
        demo: [{ say: L('OBS.', 'OBS.'), events: [SK('pfd', 'OBS')] },
          { say: L('CRS a 090.', 'CRS to 090.'), events: [(s) => K('pfd', 'crsbaro', 'inner', angleDiff(90, s.sel.obsCrs))] }] },
      { kind: 'quiz', id: 'l6.q1', q: L('Aguja del CDI en magenta significa fuente…', 'A magenta CDI needle means the source is…'),
        options: [L('GPS', 'GPS'), L('VOR1', 'VOR1'), L('VOR2', 'VOR2')], answer: 0, why: L('Magenta = GPS; verde = VOR/LOC.', 'Magenta = GPS; green = VOR/LOC.') },
      { kind: 'quiz', id: 'l6.q2', q: L('En ruta, la desviación máxima de la aguja GPS (2 puntos) equivale a…', 'Enroute, full-scale GPS needle deflection (2 dots) is…'),
        options: [L('2 NM', '2 NM'), L('10°', '10°'), L('0.3 NM', '0.3 NM')], answer: 0,
        why: L('ENR 2.0 NM, terminal 1.0 NM, aproximación 0.3 NM o angular. El VOR es angular (10°).', 'ENR 2.0 NM, terminal 1.0 NM, approach 0.3 NM or angular. The VOR is angular (10°).') },
      { kind: 'quiz', id: 'l6.q3', q: L('¿Qué hace OBS en GPS?', 'What does OBS do with the GPS?'),
        options: [L('Deja elegir el curso al waypoint y suspende la secuencia', 'Lets you pick the course to the waypoint and suspends sequencing'), L('Cancela el Direct-To', 'Cancels the Direct-To'), L('Cambia a VOR', 'Switches to VOR')], answer: 0,
        why: L('Útil para entrar a un patrón o a una espera con un curso concreto.', 'Useful to join a pattern or a hold on a given course.') },
    ],
  },
  // ------------------------------------------------------------------ 7
  {
    id: 'l7', n: 7,
    title: L('El MFD y el plan de vuelo', 'The MFD and the flight plan'),
    objectives: {
      es: ['Moverse por los grupos de páginas', 'Configurar el mapa', 'Crear, editar y activar un plan de vuelo'],
      en: ['Move through the page groups', 'Set up the map', 'Create, edit and activate a flight plan'],
    },
    steps: [
      { kind: 'scene', scene: 'cockpit', cues: [{ focus: 'mfd', label: L('MFD', 'MFD') }, { focus: 'fmsMfd', label: L('Knob FMS', 'FMS knob') }],
        caption: L('FMS grande: grupo de páginas (MAP, WPT, AUX, NRST). FMS pequeño: página dentro del grupo. Empujar FMS: cursor.',
          'Large FMS: page group (MAP, WPT, AUX, NRST). Small FMS: page in the group. Push FMS: cursor.') },
      { kind: 'task', id: 'l7.groups', setup: { scenario: 'enroute' }, part: 'mfd.pageGroup',
        task: L('Lleva el MFD al grupo NRST.', 'Take the MFD to the NRST group.'), hint: L('FMS grande; mira el indicador abajo a la derecha.', 'Large FMS; watch the indicator at the bottom right.'),
        why: L('NRST está a un giro del mapa: es el grupo de emergencia.', 'NRST is one click from the map: it is the emergency group.'),
        check: (s) => s.mfd.group === 'NRST', demo: [{ say: L('FMS grande −1.', 'Large FMS −1.'), events: [K('mfd', 'fms', 'outer', -1)] }] },
      { kind: 'task', id: 'l7.aux', setup: { scenario: 'enroute' }, part: 'mfd.pageGroup',
        task: L('Abre AUX › GPS Status.', 'Open AUX › GPS Status.'), hint: L('FMS grande hasta AUX, FMS pequeño a la segunda página.', 'Large FMS to AUX, small FMS to the second page.'),
        why: L('Aquí ves satélites, precisión y si WAAS está en uso.', 'Here you see satellites, accuracy and whether WAAS is in use.'),
        check: (s) => pageId(s) === 'AUX_GPS', demo: [{ say: L('AUX y página 2.', 'AUX and page 2.'), events: [K('mfd', 'fms', 'outer', 2), K('mfd', 'fms', 'inner', 1)] }] },
      { kind: 'task', id: 'l7.clr', setup: { scenario: 'enroute', apply: (s) => { s.mfd.group = 'AUX'; s.mfd.page = 1; } }, part: 'key.clr',
        task: L('Vuelve al mapa de un golpe.', 'Get back to the map in one go.'), hint: L('Mantén CLR del MFD unos 2 s.', 'Hold the MFD CLR for about 2 s.'),
        why: L('El atajo más útil del MFD cuando te pierdes entre páginas.', 'The most useful MFD shortcut when you get lost in the pages.'),
        check: (s) => pageId(s) === 'MAP_NAV' && !s.mfd.win, demo: [{ say: L('CLR mantenido.', 'CLR held.'), events: [KEY('mfd', 'clr', true)] }] },
      { kind: 'task', id: 'l7.orient', setup: { scenario: 'enroute' }, part: 'mfd.map',
        task: L('Pon el mapa en Track Up.', 'Set the map to Track Up.'), hint: L('MENU en la página del mapa, ENT.', 'MENU on the map page, ENT.'),
        why: L('Track Up gira el mapa con tu trayectoria: lo de delante queda arriba.', 'Track Up turns the map with your track: what is ahead is up.'),
        check: (s) => s.mfd.orient === 'track', demo: [{ say: L('MENU, ENT.', 'MENU, ENT.'), events: [KEY('mfd', 'menu'), KEY('mfd', 'ent')] }] },
      { kind: 'task', id: 'l7.range', setup: { scenario: 'enroute' }, part: 'k.range',
        task: L('Cambia la escala del mapa a 10 NM.', 'Change the map range to 10 NM.'), hint: L('Knob RANGE del MFD.', 'MFD RANGE knob.'),
        why: L('Escala corta cerca del aeródromo, larga en ruta.', 'Short range near the airport, long range enroute.'),
        check: (s) => s.mfd.range === 10, demo: [{ say: L('RANGE −2.', 'RANGE −2.'), events: [K('mfd', 'range', 'inner', -2)] }] },
      { kind: 'task', id: 'l7.fpl', setup: { scenario: 'enroute' }, part: 'mfd.fpl',
        task: L('Crea el plan SQ01 → MIRA → SQ02.', 'Create the plan SQ01 → MIRA → SQ02.'),
        hint: L('FPL, empuja FMS, escribe cada punto y ENT.', 'FPL, push FMS, type each waypoint and ENT.'),
        why: L('Cada punto se inserta antes del renglón marcado; al tener dos, el primer tramo se activa.', 'Each waypoint is inserted before the highlighted row; with two, the first leg activates.'),
        check: (s) => s.gps.fpl.legs.join() === 'SQ01,MIRA,SQ02' && s.gps.fpl.active >= 1,
        demo: [{ say: L('FPL y cursor.', 'FPL and cursor.'), events: [KEY('mfd', 'fpl'), P('mfd', 'fms')] },
          { say: L('SQ01 ENT.', 'SQ01 ENT.'), events: [...TYPE('mfd', 'SQ01'), KEY('mfd', 'ent')] },
          { say: L('MIRA ENT.', 'MIRA ENT.'), events: [...TYPE('mfd', 'MIRA'), KEY('mfd', 'ent')] },
          { say: L('SQ02 ENT.', 'SQ02 ENT.'), events: [...TYPE('mfd', 'SQ02'), KEY('mfd', 'ent')] }] },
      { kind: 'task', id: 'l7.activate', setup: { scenario: 'enroute', apply: (s) => { s.gps.fpl = { legs: ['SQ01', 'MIRA', 'SQ02'], active: 1 }; s.mfd.win = 'fpl'; } }, part: 'mfd.fpl',
        task: L('Activa el tramo hacia SQ02.', 'Activate the leg to SQ02.'), hint: L('Empuja FMS, cursor sobre SQ02, MENU › Activar tramo, ENT.', 'Push FMS, cursor on SQ02, MENU › Activate leg, ENT.'),
        why: L('Saltas un punto sin borrar el plan.', 'You skip a waypoint without deleting the plan.'),
        check: (s) => s.gps.fpl.active === 2,
        demo: [{ say: L('Cursor a SQ02.', 'Cursor to SQ02.'), events: [P('mfd', 'fms'), K('mfd', 'fms', 'outer', 2)] }, { say: L('MENU, ENT.', 'MENU, ENT.'), events: [KEY('mfd', 'menu'), KEY('mfd', 'ent')] }] },
      { kind: 'quiz', id: 'l7.q1', q: L('Con el cursor apagado, el FMS grande…', 'With the cursor off, the large FMS…'),
        options: [L('Cambia de grupo de páginas', 'Changes page group'), L('Cambia la escala', 'Changes range'), L('Cambia de página dentro del grupo', 'Changes page within the group')], answer: 0,
        why: L('El pequeño cambia de página dentro del grupo.', 'The small one changes page within the group.') },
      { kind: 'quiz', id: 'l7.q2', q: L('Al escribir un punto en el FPL, ¿dónde se inserta?', 'When you enter a waypoint in the FPL, where does it go?'),
        options: [L('Antes del renglón resaltado', 'Before the highlighted row'), L('Siempre al final', 'Always at the end'), L('Reemplaza al resaltado', 'It replaces the highlighted one')], answer: 0,
        why: L('Para añadir al final, pon el cursor en el renglón vacío.', 'To add at the end, put the cursor on the empty row.') },
      { kind: 'quiz', id: 'l7.q3', q: L('Para borrar un punto del FPL…', 'To delete a waypoint from the FPL…'),
        options: [L('Cursor sobre él, CLR y ENT para confirmar', 'Cursor on it, CLR and ENT to confirm'), L('Mantener ENT', 'Hold ENT'), L('D→ y MENU', 'D→ and MENU')], answer: 0,
        why: L('El G1000 siempre pide confirmación antes de borrar.', 'The G1000 always asks for confirmation before deleting.') },
    ],
  },
  // ------------------------------------------------------------------ 8
  {
    id: 'l8', n: 8,
    title: L('El PFD a fondo', 'The PFD in depth'),
    objectives: {
      es: ['Usar el mapa inset y los punteros de rumbo', 'Cambiar la fuente del CDI', 'Fijar mínimos, STD BARO y sincronizar HDG'],
      en: ['Use the inset map and bearing pointers', 'Change the CDI source', 'Set minimums, STD BARO and sync HDG'],
    },
    steps: [
      { kind: 'scene', scene: 'cockpit', cues: [{ focus: 'softkeysPfd', label: L('Softkeys del PFD', 'PFD softkeys') }, { focus: 'hdgKnob', label: L('HDG', 'HDG') }],
        caption: L('Las softkeys del PFD configuran lo que ves: mapa inset, punteros, fuente del CDI, mínimos.',
          'The PFD softkeys configure what you see: inset map, pointers, CDI source, minimums.') },
      { kind: 'task', id: 'l8.inset', setup: { scenario: 'enroute' }, part: 'pfd.inset',
        task: L('Muestra el mapa inset en el PFD.', 'Show the inset map on the PFD.'), hint: L('Softkey INSET.', 'INSET softkey.'),
        why: L('Un mapa pequeño junto al HSI evita mirar al MFD en momentos de carga.', 'A small map next to the HSI saves looking at the MFD when busy.'),
        check: (s) => s.pfd.inset, demo: [{ say: L('INSET.', 'INSET.'), events: [SK('pfd', 'INSET')] }] },
      { kind: 'task', id: 'l8.brg1', setup: { scenario: 'enroute' }, part: 'pfd.hsi',
        task: L('Muestra el puntero BRG1 hacia la estación de NAV1.', 'Show the BRG1 pointer to the NAV1 station.'), hint: L('PFD → BRG1.', 'PFD → BRG1.'),
        why: L('El puntero apunta a la estación como un ADF/RMI: útil para cruces de radial.', 'The pointer points at the station like an ADF/RMI: useful for radial cross-checks.'),
        check: (s) => s.pfd.brg1 === 'nav1', demo: [{ say: L('PFD → BRG1.', 'PFD → BRG1.'), events: [SK('pfd', 'PFD'), SK('pfd', 'BRG1')] }] },
      { kind: 'task', id: 'l8.cdi', setup: { scenario: 'enroute' }, part: 'pfd.hsi',
        task: L('Elige VOR2 como fuente del CDI.', 'Select VOR2 as CDI source.'), hint: L('CDI dos veces: GPS → VOR1 → VOR2.', 'CDI twice: GPS → VOR1 → VOR2.'),
        why: L('Mira siempre la etiqueta de fuente en el HSI antes de seguir una aguja.', 'Always read the source label on the HSI before following a needle.'),
        check: (s) => s.pfd.cdi === 'VOR2', demo: [{ say: L('CDI, CDI.', 'CDI, CDI.'), events: [SK('pfd', 'CDI'), SK('pfd', 'CDI')] }] },
      { kind: 'task', id: 'l8.mins', setup: { scenario: 'enroute' }, part: 'pfd.alt',
        task: L('Fija los mínimos en 500 ft.', 'Set minimums to 500 ft.'), hint: L('TMR/REF y FMS del PFD; CLR para cerrar.', 'TMR/REF and the PFD FMS; CLR to close.'),
        why: L('El G1000 avisa al llegar a los mínimos con un bug en la cinta de altitud.', 'The G1000 alerts at minimums with a bug on the altitude tape.'),
        check: (s) => s.sel.mins === 500,
        demo: [{ say: L('TMR/REF.', 'TMR/REF.'), events: [SK('pfd', 'TMR/REF')] }, { say: L('FMS hasta 500.', 'FMS to 500.'), events: [K('pfd', 'fms', 'inner', 1), K('pfd', 'fms', 'inner', -1)] }] },
      { kind: 'task', id: 'l8.std', setup: { scenario: 'enroute' }, part: 'pfd.baro',
        task: L('Sube por la altitud de transición: pon STD BARO.', 'Climbing through the transition altitude: set STD BARO.'), hint: L('PFD → STD BARO.', 'PFD → STD BARO.'),
        why: L('Por encima de la transición todos vuelan con 29.92 (niveles de vuelo).', 'Above transition everyone flies on 29.92 (flight levels).'),
        check: (s) => near(s.sel.baro, 29.92), demo: [{ say: L('PFD → STD BARO.', 'PFD → STD BARO.'), events: [SK('pfd', 'PFD'), SK('pfd', 'STD BARO')] }] },
      { kind: 'task', id: 'l8.hdgSync', setup: { scenario: 'enroute', apply: (s) => { s.sel.hdg = 200; s.gps.dto = { id: 'SQ04', from: { lat: s.ac.lat, lon: s.ac.lon } }; } }, part: 'k.hdg',
        task: L('Lleva el bug de rumbo a tu rumbo actual de un toque.', 'Bring the heading bug to your current heading in one press.'), hint: L('Empuja el knob HDG.', 'Push the HDG knob.'),
        why: L('Antes de usar el bug como referencia, sincronízalo para no virar por sorpresa.', 'Before using the bug as a reference, sync it so you do not turn by surprise.'),
        check: (s) => Math.abs(angleDiff(s.sel.hdg, norm360(s.ac.hdg))) <= 2, demo: [{ say: L('HDG push.', 'HDG push.'), events: [P('pfd', 'hdg')] }] },
      { kind: 'quiz', id: 'l8.q1', q: L('Un puntero BRG apunta…', 'A BRG pointer points…'),
        options: [L('A la estación o waypoint elegido', 'At the selected station or waypoint'), L('Al rumbo seleccionado', 'At the selected heading'), L('Al viento', 'At the wind')], answer: 0,
        why: L('La cola indica el radial en el que estás.', 'The tail shows the radial you are on.') },
      { kind: 'quiz', id: 'l8.q2', q: L('STD BARO pone el altímetro en…', 'STD BARO sets the altimeter to…'),
        options: [L('29.92 inHg (1013 hPa)', '29.92 inHg (1013 hPa)'), L('La elevación del campo', 'Field elevation'), L('30.12', '30.12')], answer: 0,
        why: L('Es la presión estándar ISA.', 'It is the ISA standard pressure.') },
      { kind: 'quiz', id: 'l8.q3', q: L('¿Dónde se ve la fuente activa del CDI?', 'Where is the active CDI source shown?'),
        options: [L('Una etiqueta (GPS/VOR1/VOR2) dentro del HSI', 'A label (GPS/VOR1/VOR2) inside the HSI'), L('En el MFD', 'On the MFD'), L('En el panel de audio', 'On the audio panel')], answer: 0,
        why: L('Junto con el color de la aguja, confirma qué estás siguiendo.', 'Along with the needle colour, it confirms what you are following.') },
    ],
  },
];

/** Garmin ground lessons 9–13: listed as coming soon. */
export const COMING = [
  { n: 9, title: L('Emergencias y modo reversionario', 'Emergencies and reversionary mode') },
  { n: 10, title: L('Terreno y TAWS', 'Terrain and TAWS') },
  { n: 11, title: L('Tráfico', 'Traffic') },
  { n: 12, title: L('Meteorología', 'Weather') },
  { n: 13, title: L('Autopiloto GFC 700', 'GFC 700 autopilot') },
];

/** Ids of the steps that count for progress (tasks and quizzes). */
export const progressIds = (lesson) => lesson.steps.filter((s) => s.kind === 'task' || s.kind === 'quiz').map((s) => /** @type {any} */ (s).id);
