// Explain-mode content: one entry per data-part id drawn on the G1000 (2D), the switches, and the LRUs of the
// exploded scene. Each entry has es + en with { title, what, read, why }. Glossary terms become tooltips at render.

/** @typedef {{ title: string, what: string, read: string, why: string }} PartText */
const P = (es, en) => ({ es: { title: es[0], what: es[1], read: es[2], why: es[3] }, en: { title: en[0], what: en[1], read: en[2], why: en[3] } });

/** @type {Record<string, {es: PartText, en: PartText}>} */
export const PARTS = {
  // ---------- PFD
  'pfd.att': P(['Horizonte artificial', 'Actitud del avión (cabeceo y alabeo) del AHRS, a todo el ancho de la pantalla.', 'El símbolo amarillo es el avión; las líneas, grados de cabeceo; el arco superior, el alabeo.', 'Es el centro del scan: todo lo demás se mira alrededor.'],
    ['Attitude indicator', 'Aircraft attitude (pitch and bank) from the AHRS, across the whole screen.', 'The yellow symbol is the aircraft; the lines are degrees of pitch; the top arc, the bank.', 'It is the centre of the scan: everything else is read around it.']),
  'pfd.ias': P(['Cinta de velocidad', 'Velocidad indicada (IAS) del ADC en nudos, con los arcos del C172.', 'Número central = velocidad actual. Arco blanco: flaps; verde: normal; amarillo: precaución; rojo: VNE. La línea magenta es la tendencia a 6 s.', 'Mismos colores que el anemómetro clásico, con el número exacto al lado.'],
    ['Airspeed tape', 'Indicated airspeed (IAS) from the ADC in knots, with the C172 arcs.', 'Centre number = current airspeed. White arc: flaps; green: normal; yellow: caution; red: VNE. The magenta line is the 6-second trend.', 'Same colours as the classic airspeed indicator, with the exact number beside them.']),
  'pfd.alt': P(['Cinta de altitud', 'Altitud indicada del ADC, corregida con tu ajuste BARO.', 'Número central = altitud. Arriba en cian, la altitud seleccionada; el bug de mínimos aparece cuando los fijas.', 'Muestra la tendencia vertical y la altitud elegida juntas.'],
    ['Altitude tape', 'Indicated altitude from the ADC, corrected with your BARO setting.', 'Centre number = altitude. In cyan on top, the selected altitude; the minimums bug shows when set.', 'It shows the vertical trend and the chosen altitude together.']),
  'pfd.vsi': P(['Velocidad vertical (VSI)', 'Régimen de ascenso o descenso del ADC.', 'El puntero con el valor en pies por minuto; ±2000 de escala.', 'Para ascensos y descensos estables.'],
    ['Vertical speed (VSI)', 'Climb or descent rate from the ADC.', 'The pointer carries the value in feet per minute; ±2000 scale.', 'For stable climbs and descents.']),
  'pfd.hsi': P(['HSI', 'Indicador de situación horizontal: rosa de rumbos del AHRS más la aguja de curso (CDI).', 'Arriba, el rumbo. La flecha es el curso, su centro la desviación; magenta = GPS, verde = VOR. La etiqueta indica la fuente.', 'Rumbo y navegación en un instrumento: no hay que cruzar datos de dos relojes.'],
    ['HSI', 'Horizontal situation indicator: AHRS compass rose plus the course needle (CDI).', 'Heading at the top. The arrow is the course, its centre the deviation; magenta = GPS, green = VOR. The label shows the source.', 'Heading and navigation in one instrument: no cross-checking two gauges.']),
  'pfd.slip': P(['Indicador de derrape', 'El trapecio bajo el puntero de alabeo: la “bola” del coordinador.', 'Si se desplaza, pisa el pedal de ese lado.', 'Vuelo coordinado = menos resistencia y sin riesgo de barrena en virajes lentos.'],
    ['Slip/skid indicator', 'The trapezoid under the roll pointer: the turn coordinator “ball”.', 'If it moves aside, step on that side’s rudder.', 'Coordinated flight = less drag and no spin risk in slow turns.']),
  'pfd.selAlt': P(['Altitud seleccionada', 'La altitud que eliges con el knob ALT, en cian sobre la cinta.', 'Grande: miles. Pequeño: cientos.', 'Alerta al acercarte y al desviarte de ella.'],
    ['Selected altitude', 'The altitude you pick with the ALT knob, in cyan above the tape.', 'Large: thousands. Small: hundreds.', 'Alerts when approaching and deviating from it.']),
  'pfd.baro': P(['Ajuste altimétrico', 'El valor BARO bajo la cinta de altitud, en inHg.', 'Anillo grande del knob CRS/BARO; STD BARO pone 29.92.', '0.01 inHg ≈ 10 ft: un ajuste viejo te pone a otra altura.'],
    ['Altimeter setting', 'The BARO value under the altitude tape, in inHg.', 'Large ring of the CRS/BARO knob; STD BARO sets 29.92.', '0.01 inHg ≈ 10 ft: an old setting puts you at another height.']),
  'pfd.xpdrBox': P(['Caja del transponder', 'Código, modo y la hora local abajo a la derecha.', 'Verde = ALT/ON; blanco = STBY; “IDNT” mientras dura el ident.', 'Así verificas lo que estás enviando al radar.'],
    ['Transponder box', 'Code, mode and local time at the bottom right.', 'Green = ALT/ON; white = STBY; “IDNT” while the ident lasts.', 'It is how you verify what you are sending to radar.']),
  'pfd.comBox': P(['Radios COM', 'COM1 y COM2: activa a la izquierda, standby a la derecha.', 'Activa verde = transmites por ella. Caja cian = la que sintonizas.', 'Ves las dos radios sin mirar otro panel.'],
    ['COM radios', 'COM1 and COM2: active on the left, standby on the right.', 'Green active = you transmit on it. Cyan box = the one you are tuning.', 'You see both radios without looking at another panel.']),
  'pfd.navBox': P(['Radios NAV', 'NAV1 y NAV2 arriba a la izquierda, con el identificador decodificado.', 'Activa a la derecha, standby a la izquierda; caja cian = la que sintonizas.', 'Comprueba el identificador antes de usar un VOR.'],
    ['NAV radios', 'NAV1 and NAV2 at the top left, with the decoded identifier.', 'Active on the right, standby on the left; cyan box = the one being tuned.', 'Check the identifier before using a VOR.']),
  'pfd.navStatus': P(['Barra de estado de navegación', 'El tramo activo, la distancia y el rumbo deseado (DTK).', '“→ SQ04  DIS 23.4NM  DTK 327°”.', 'Un vistazo y sabes adónde vas.'],
    ['Navigation status bar', 'The active leg, the distance and the desired track (DTK).', '“→ SQ04  DIS 23.4NM  DTK 327°”.', 'One glance and you know where you are going.']),
  'pfd.inset': P(['Mapa inset', 'Un mapa pequeño abajo a la izquierda del PFD.', 'Escala con el knob RANGE del PFD.', 'Situación sin girar la cabeza al MFD.'],
    ['Inset map', 'A small map at the bottom left of the PFD.', 'Range with the PFD RANGE knob.', 'Awareness without turning to the MFD.']),
  'pfd.nrst': P(['Ventana NRST', 'Los aeródromos más cercanos con rumbo y distancia.', 'Empuja FMS para el cursor; D→ con uno resaltado.', 'El camino más corto a un aeródromo en emergencia.'],
    ['NRST window', 'The nearest airports with bearing and distance.', 'Push FMS for the cursor; D→ with one highlighted.', 'The shortest way to an airport in an emergency.']),
  'pfd.softkeys': P(['Softkeys', '12 teclas bajo la pantalla cuyo nombre cambia según el menú.', 'La etiqueta encima dice qué hace; resaltada = activa. BACK sube un nivel.', 'Todo lo del PFD que no tiene knob propio.'],
    ['Softkeys', '12 keys under the screen whose label changes with the menu.', 'The label above says what it does; highlighted = on. BACK goes up a level.', 'Everything on the PFD without its own knob.']),
  'mfd.softkeys': P(['Softkeys del MFD', '12 teclas bajo el MFD: ENGINE, MAP, DCLTR…', 'La etiqueta dice qué hace; BACK sube un nivel.', 'Cambian el EIS y las capas del mapa.'],
    ['MFD softkeys', '12 keys under the MFD: ENGINE, MAP, DCLTR…', 'The label says what it does; BACK goes up a level.', 'They change the EIS and the map layers.']),
  // ---------- bezel
  'k.nav': P(['Knob NAV', 'Doble: grande MHz, pequeño 50 kHz. Empujar alterna NAV1/NAV2.', 'Sintoniza la standby de la radio con caja cian.', 'Los VOR van de 108.00 a 117.95.'],
    ['NAV knob', 'Dual: large MHz, small 50 kHz. Push toggles NAV1/NAV2.', 'Tunes the standby of the radio in the cyan box.', 'VORs run from 108.00 to 117.95.']),
  'k.com': P(['Knob COM', 'Doble: grande MHz, pequeño 25 kHz. Empujar alterna COM1/COM2.', 'Sintoniza la standby; ⇆ la pasa a activa.', 'Siempre preparas antes de cambiar.'],
    ['COM knob', 'Dual: large MHz, small 25 kHz. Push toggles COM1/COM2.', 'Tunes the standby; ⇆ makes it active.', 'You always prepare before switching.']),
  'k.hdg': P(['Knob HDG', 'Mueve el bug de rumbo (cian) del HSI. Empujar = sincronizar con el rumbo actual.', 'Valor en la ventana “HDG” junto al HSI.', 'Referencia de rumbo; con autopiloto, el rumbo a volar.'],
    ['HDG knob', 'Moves the heading bug (cyan) on the HSI. Push = sync to current heading.', 'Value in the “HDG” window next to the HSI.', 'A heading reference; with an autopilot, the heading to fly.']),
  'k.alt': P(['Knob ALT', 'Doble: grande ±1000 ft, pequeño ±100 ft.', 'La altitud seleccionada sale en cian sobre la cinta.', 'Fija la altitud asignada y recibe alertas.'],
    ['ALT knob', 'Dual: large ±1000 ft, small ±100 ft.', 'The selected altitude shows in cyan above the tape.', 'Set the assigned altitude and get alerts.']),
  'k.crsbaro': P(['Knob CRS/BARO', 'Grande: ajuste altimétrico. Pequeño: curso del CDI (VOR u OBS). Empujar: centra el curso con TO.', 'CRS se ve en el HSI; BARO bajo la cinta de altitud.', 'Dos ajustes críticos en un knob: mira cuál giras.'],
    ['CRS/BARO knob', 'Large: altimeter setting. Small: CDI course (VOR or OBS). Push: centres the course with TO.', 'CRS shows on the HSI; BARO under the altitude tape.', 'Two critical settings on one knob: watch which one you turn.']),
  'k.range': P(['Knob RANGE', 'Escala del mapa (inset en el PFD, mapa en el MFD). En el MFD, empujar activa el paneo.', 'Girar a la derecha aleja.', 'La escala correcta para cada fase.'],
    ['RANGE knob', 'Map range (inset on the PFD, map on the MFD). On the MFD, push turns panning on.', 'Clockwise zooms out.', 'The right range for each phase.']),
  'k.fms': P(['Knob FMS', 'Doble. Sin cursor: grande = grupo de páginas, pequeño = página. Empujar = cursor. Con cursor: grande mueve, pequeño edita.', 'Para escribir: pequeño cambia la letra, grande pasa a la siguiente.', 'El knob que más usarás en el G1000.'],
    ['FMS knob', 'Dual. No cursor: large = page group, small = page. Push = cursor. With cursor: large moves, small edits.', 'To type: small changes the letter, large moves to the next.', 'The knob you will use most on the G1000.']),
  'key.dto': P(['Tecla D→ (Direct-To)', 'Abre la ventana Direct-To con el punto resaltado o el destino actual.', 'ENT confirma el identificador, ENT activa.', 'Directo a cualquier punto en tres pulsaciones.'],
    ['D→ (Direct-To) key', 'Opens the Direct-To window with the highlighted point or the current destination.', 'ENT confirms the identifier, ENT activates.', 'Direct to any point in three presses.']),
  'key.menu': P(['Tecla MENU', 'Opciones de la página o ventana actual.', 'FMS para elegir, ENT para ejecutar, CLR para cerrar.', 'Lo menos usado está aquí: activar tramo, orientación del mapa…'],
    ['MENU key', 'Options for the current page or window.', 'FMS to pick, ENT to run, CLR to close.', 'The less-used things live here: activate leg, map orientation…']),
  'key.fpl': P(['Tecla FPL', 'Abre o cierra el plan de vuelo activo.', 'Empuja FMS para el cursor; escribe para insertar.', 'El plan es la base del GPS.'],
    ['FPL key', 'Opens or closes the active flight plan.', 'Push FMS for the cursor; type to insert.', 'The plan is the backbone of the GPS.']),
  'key.clr': P(['Tecla CLR', 'Borra, cancela o cierra. Mantenida 2 s en el MFD vuelve al mapa.', 'Una pulsación = un paso atrás.', 'La salida de cualquier pantalla.'],
    ['CLR key', 'Clears, cancels or closes. Held 2 s on the MFD returns to the map.', 'One press = one step back.', 'The way out of any screen.']),
  'key.ent': P(['Tecla ENT', 'Acepta un dato o confirma una pregunta.', 'Tras escribir, ENT; ante “¿Activar?”, ENT.', 'Nada cambia hasta que confirmas.'],
    ['ENT key', 'Accepts an entry or confirms a prompt.', 'After typing, ENT; at “Activate?”, ENT.', 'Nothing changes until you confirm.']),
  'key.proc': P(['Tecla PROC', 'Procedimientos: salidas, llegadas y aproximaciones.', 'Se verá en el módulo IFR (próximamente).', 'Cargar una aproximación desde la base de datos evita errores.'],
    ['PROC key', 'Procedures: departures, arrivals and approaches.', 'Covered in the IFR module (coming soon).', 'Loading an approach from the database avoids errors.']),
  'key.comSwap': P(['Tecla ⇆ COM', 'Intercambia activa y standby de la COM con caja cian.', 'Una pulsación.', 'Si no contestan, ⇆ otra vez y vuelves.'],
    ['COM ⇆ key', 'Swaps active and standby of the COM in the cyan box.', 'One press.', 'If nobody answers, ⇆ again takes you back.']),
  'key.navSwap': P(['Tecla ⇆ NAV', 'Intercambia activa y standby de la NAV con caja cian.', 'Una pulsación.', 'Prepara el siguiente VOR antes de necesitarlo.'],
    ['NAV ⇆ key', 'Swaps active and standby of the NAV in the cyan box.', 'One press.', 'Prepare the next VOR before you need it.']),
  // ---------- MFD
  'mfd.eis': P(['EIS', 'Sistema de indicación de motor: RPM, flujo, aceite, EGT, combustible, voltios y amperios.', 'Agujas en verde = normal. ENGINE / LEAN / SYSTEM cambian la vista.', 'Un vistazo a las agujas basta; los números son para confirmar.'],
    ['EIS', 'Engine indication system: RPM, fuel flow, oil, EGT, fuel, volts and amps.', 'Pointers in the green = normal. ENGINE / LEAN / SYSTEM change the view.', 'A glance at the pointers is enough; the numbers are to confirm.']),
  'mfd.map': P(['Mapa de navegación', 'Tu avión, la ruta magenta, aeródromos, VOR y waypoints.', 'Escala abajo a la derecha; orientación arriba (North/Track Up).', 'Conciencia situacional de un vistazo.'],
    ['Navigation map', 'Your aircraft, the magenta route, airports, VORs and waypoints.', 'Range at the bottom right; orientation at the top (North/Track Up).', 'Situational awareness at a glance.']),
  'mfd.pageGroup': P(['Indicador de páginas', 'Grupo actual (MAP, WPT, AUX, NRST) y cuántas páginas tiene.', 'El grupo en cian, la página como casilla rellena.', 'Saber dónde estás evita perderse entre páginas.'],
    ['Page indicator', 'Current group (MAP, WPT, AUX, NRST) and how many pages it has.', 'The group in cyan, the page as a filled box.', 'Knowing where you are avoids getting lost in the pages.']),
  'mfd.page': P(['Página del MFD', 'La página elegida con el knob FMS.', 'El título arriba; empuja FMS para el cursor.', 'Cada página responde a una pregunta: ¿dónde?, ¿qué frecuencia?, ¿cuál es el más cercano?'],
    ['MFD page', 'The page chosen with the FMS knob.', 'Title at the top; push FMS for the cursor.', 'Each page answers a question: where?, which frequency?, which is nearest?']),
  'mfd.fpl': P(['Plan de vuelo activo', 'Lista de puntos con DTK y distancia de cada tramo; el tramo activo con flecha magenta.', 'Renglón vacío al final para añadir.', 'Lo que el GPS va a volar, en orden.'],
    ['Active flight plan', 'List of waypoints with DTK and distance of each leg; the active leg with a magenta arrow.', 'Empty row at the end to add.', 'What the GPS is going to fly, in order.']),
  // ---------- audio panel and switches
  'audio.panel': P(['Panel de audio GMA 1347', 'Elige con qué radio transmites (MIC) y cuáles escuchas.', 'Tecla iluminada = activa. COM MIC también activa su escucha.', 'Puedes oír ATIS en COM2 mientras hablas por COM1.'],
    ['GMA 1347 audio panel', 'Picks which radio you transmit on (MIC) and which you hear.', 'Lit key = on. COM MIC also turns its audio on.', 'You can hear the ATIS on COM2 while talking on COM1.']),
  'audio.backup': P(['DISPLAY BACKUP', 'Botón rojo del panel de audio: modo reversionario manual.', 'Con una pantalla fallada, ambas muestran PFD + EIS.', 'Lo verás en la lección de emergencias (próximamente).'],
    ['DISPLAY BACKUP', 'Red button on the audio panel: manual reversionary mode.', 'With a display failed, both show PFD + EIS.', 'Covered in the emergencies lesson (coming soon).']),
  'sw.master': P(['MASTER', 'Batería y alternador. Da energía al bus esencial (PFD).', 'Arriba = ON.', 'Primer interruptor del arranque.'],
    ['MASTER', 'Battery and alternator. Powers the essential bus (PFD).', 'Up = ON.', 'First switch of the start-up.']),
  'sw.avionics': P(['AVIONICS', 'Bus de aviónica: MFD, COM2/NAV2 y el resto.', 'Arriba = ON, después del arranque del motor en la práctica real.', 'Protege la aviónica de picos del arranque.'],
    ['AVIONICS', 'Avionics bus: MFD, COM2/NAV2 and the rest.', 'Up = ON, after engine start in real practice.', 'Protects the avionics from start-up spikes.']),
  'sw.engine': P(['Arranque', 'Llave de magnetos/arranque, simplificada a un interruptor.', 'ON = motor en marcha.', 'Sin MASTER no hay arranque.'],
    ['Starter', 'Magneto/start key, simplified to one switch.', 'ON = engine running.', 'No MASTER, no start.']),
  // ---------- LRUs (exploded scene)
  'lru.gdu': P(['GDU 1040', 'Pantalla de 10.4": PFD o MFD (son intercambiables).', 'Muestra lo que le llega de su GIA.', 'Si una falla, la otra pasa a modo reversionario.'],
    ['GDU 1040', '10.4" display: PFD or MFD (they are interchangeable).', 'Shows what arrives from its GIA.', 'If one fails, the other goes reversionary.']),
  'lru.gia': P(['GIA 63W', 'Unidad integrada: GPS/WAAS, COM, NAV/ILS y procesamiento.', 'GIA1 con el PFD, GIA2 con el MFD.', 'Redundancia: dos GPS y dos juegos de radios.'],
    ['GIA 63W', 'Integrated unit: GPS/WAAS, COM, NAV/ILS and processing.', 'GIA1 with the PFD, GIA2 with the MFD.', 'Redundancy: two GPS and two sets of radios.']),
  'lru.ahrs': P(['GRS 77 AHRS', 'Sensores de estado sólido de actitud y rumbo.', 'Alimenta horizonte y HSI.', 'Si falla: X rojas en actitud y rumbo.'],
    ['GRS 77 AHRS', 'Solid-state attitude and heading sensors.', 'Feeds the horizon and the HSI.', 'If it fails: red X’s on attitude and heading.']),
  'lru.gmu': P(['GMU 44', 'Magnetómetro en el ala: da el norte magnético al AHRS.', 'No se ve en cabina.', 'Sin él, el rumbo se degrada.'],
    ['GMU 44', 'Magnetometer in the wing: gives magnetic north to the AHRS.', 'Not visible in the cockpit.', 'Without it, heading degrades.']),
  'lru.adc': P(['GDC 74A ADC', 'Computadora de datos de aire.', 'Convierte pitot, estática y OAT en IAS, altitud, VSI y TAS.', 'Si falla: X rojas en las cintas.'],
    ['GDC 74A ADC', 'Air data computer.', 'Turns pitot, static and OAT into IAS, altitude, VSI and TAS.', 'If it fails: red X’s on the tapes.']),
  'lru.pitot': P(['Pitot, estática y OAT', 'Tomas de presión y sonda de temperatura.', 'Entradas del ADC.', 'Un pitot tapado engaña al ADC igual que al anemómetro clásico.'],
    ['Pitot, static and OAT', 'Pressure ports and temperature probe.', 'ADC inputs.', 'A blocked pitot fools the ADC just like the classic airspeed indicator.']),
  'lru.gea': P(['GEA 71', 'Adquisición de datos de motor y sistemas.', 'Alimenta el EIS del MFD.', 'Sin él, el EIS se queda sin datos.'],
    ['GEA 71', 'Engine and systems data acquisition.', 'Feeds the MFD EIS.', 'Without it, the EIS has no data.']),
  'lru.gtx': P(['GTX 33', 'Transponder modo S remoto.', 'Se controla desde las softkeys del PFD.', 'Recibe la altitud del ADC para el modo ALT.'],
    ['GTX 33', 'Remote mode S transponder.', 'Controlled from the PFD softkeys.', 'Gets altitude from the ADC for ALT mode.']),
  'lru.gma': P(['GMA 1347', 'Panel de audio e intercomunicador.', 'Entre las dos pantallas.', 'También tiene el botón DISPLAY BACKUP.'],
    ['GMA 1347', 'Audio panel and intercom.', 'Between the two displays.', 'It also holds the DISPLAY BACKUP button.']),
  'lru.ant': P(['Antenas', 'GPS en el techo, COM y NAV en fuselaje y cola.', 'Las señales llegan a las GIA.', 'Sin antena GPS no hay posición.'],
    ['Antennas', 'GPS on the roof, COM and NAV on the fuselage and tail.', 'Signals go to the GIAs.', 'No GPS antenna, no position.']),
};
